CREATE TABLE GIT(
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL
);

INSERT INTO GIT(ID_USER, USERNAME, NAME) VALUES(1, 'gameplaybiel', 'Gabriel');
INSERT INTO GIT(ID_USER, USERNAME, NAME) VALUES(2, 'pycodebr', 'Python Code');
INSERT INTO GIT(ID_USER, USERNAME, NAME) VALUES(3, 'android', 'Android');

SELECT * FROM GIT;